name: Generate and Publish Ledger Report

on:
  push:
    branches: [main]  # or your default branch

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    name: Build Ledger Report and Publish to GitHub Pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set current year
        id: vars
        run: echo "year=$(date +%Y)" >> "$GITHUB_OUTPUT"

      - name: Generate ledger XML
        uses: addnab/docker-run-action@v3
        with:
          image: dcycle/ledger:1
          options: --rm -v ${{ github.workspace }}:/data
          run: |
            ledger -y %F -f "/data/${{ steps.vars.outputs.year }}.dat" xml > "/tmp/${{ steps.vars.outputs.year }}.xml"

      - name: Generate HTML with xsltproc
        uses: addnab/docker-run-action@v3
        with:
          image: s3v1/xsltproc
          options: --rm -v ${{ github.workspace }}:/data
          run: |
            xsltproc -o "/data/docs/${{ steps.vars.outputs.year }}.html" /data/ledger-journal.xslt "/tmp/${{ steps.vars.outputs.year }}.xml"

      - name: Add noindex to HTML
        run: |
          sed -i 's|<head>|<head><meta name="robots" content="noindex">|' "${{ steps.vars.outputs.year }}.html"

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload HTML to GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
