name: Generate and Publish Ledger Report

on:
  push:
    branches: [main]  # or your default branch

permissions:
  id-token: write
  pages: write
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    name: Build Ledger Report and Publish to GitHub Pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set current year and month
        id: vars
        run: echo "year=$(date +%Y)" >> "$GITHUB_OUTPUT"\

      - name: Generate ledger XML
        uses: addnab/docker-run-action@v3
        with:
          image: dcycle/ledger:1
          options: --rm -v ${{ github.workspace }}:/data
          run: |
            ledger -y %F -f "/data/${{ steps.vars.outputs.year }}.dat" xml > "/data/docs/report.xml"

      - name: Generate HTML with xsltproc
        uses: addnab/docker-run-action@v3
        with:
          image: s3v1/xsltproc
          options: --rm -v ${{ github.workspace }}:/data
          run: |
            xsltproc -o "/tmp/index.html" /data/ledger-journal.xslt "/data/docs/report.xml"
            rm "/data/docs/report.xml"
            cp "/tmp/index.html" "/data/docs/index.html"
            cp "/tmp/index.html" "/data/docs/$(sort "/data/${{ steps.vars.outputs.year }}.dat" |grep -E "^([0-9][0-9][0-9][0-9])-" |tail -1 |cut -d" " -f1 |cut -d- -f1,2).html"

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload HTML to GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
