name: Generate and Publish Ledger Report

on:
  push:
    branches: [main]  # or your default branch

permissions:
  id-token: write
  pages: write
  contents: write

jobs:
  build-and-publish:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    name: Build Ledger Report and Publish to GitHub Pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate ledger XML
        uses: addnab/docker-run-action@v3
        with:
          image: dcycle/ledger:1
          options: --rm -v ${{ github.workspace }}:/data
          run: |
            mkdir -p /data/docs
            chmod -R a+w /data/docs
            ledger -y %F -f "/data/$(date +%Y).dat" xml > "/data/docs/report.xml"

      - name: Generate HTML with xsltproc
        uses: addnab/docker-run-action@v3
        with:
          image: s3v1/xsltproc
          options: --rm -v ${{ github.workspace }}:/data
          run: xsltproc -o "/data/docs/index.html" /data/ledger-journal.xslt "/data/docs/report.xml"

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload HTML to GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
